# Generated by Django 4.0.3 on 2022-03-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_media_author_media_created_alter_media_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
