# Generated by Django 3.2.8 on 2022-03-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('song', models.FileField(upload_to='videos')),
                ('description', models.TextField(blank=True)),
                ('affiliate_url', models.SlugField(blank=True, null=True)),
                ('release', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The perfection of God', max_length=200)),
                ('body', models.TextField(blank=True, default=False, max_length=200, null=True)),
                ('date_noted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pics_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ebenezer', max_length=200)),
                ('body', models.TextField(blank=True, default=False, max_length=200, null=True)),
                ('affiliate_url', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(default=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Faith,Hope and Love', max_length=200)),
                ('body', models.TextField(blank=True, default=False, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scripture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The finished work of christ', max_length=200)),
                ('body', models.TextField(blank=True, default=False, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whatusay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
