# Generated by Django 4.0.3 on 2022-03-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='artist_image',
        ),
        migrations.RemoveField(
            model_name='media',
            name='post',
        ),
        migrations.RemoveField(
            model_name='media',
            name='video',
        ),
        migrations.AlterField(
            model_name='media',
            name='affiliate_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
