# Generated by Django 3.2.8 on 2022-03-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_sermonsay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermonsay',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Sermonsay',
        ),
    ]
