# Generated by Django 4.0.3 on 2022-03-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_remove_media_artist_image_remove_media_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(default='Bishop Francis Tumusiime', max_length=150),
        ),
    ]
