# Generated by Django 4.0.3 on 2022-03-24 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_media_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='author',
            field=models.CharField(default='Bishop Francis Tumusiime', max_length=150),
        ),
        migrations.AddField(
            model_name='media',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
