# Generated by Django 3.2.8 on 2022-03-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_sermonsay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, default=False, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='update',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Apostle Francis Tumusiime', max_length=150),
        ),
    ]
