# Generated by Django 3.2.8 on 2022-03-11 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20220311_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pics_day',
            options={'ordering': ['uploaded']},
        ),
        migrations.AddField(
            model_name='pics_day',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pics_day',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
