# Generated by Django 4.0.3 on 2022-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20220311_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Bishop Francis Tumusiime', max_length=150),
        ),
    ]
